server:
  port: 9080

spring:
  application:
    name: auth-server-dilithium

  datasource:
    url: jdbc:h2:file:./data/authdb-dilithium

jwt:
  signature:
    algorithm: DILITHIUM
    issuer: https://auth-server-dilithium:9080

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [DILITHIUM] [%thread] %-5level %logger{36} - %msg%n"
