server:
  port: 8080

spring:
  application:
    name: auth-server-rsa

  datasource:
    url: jdbc:h2:file:./data/authdb-rsa

jwt:
  signature:
    algorithm: RSA
    issuer: https://auth-server-rsa:8080

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [RSA] [%thread] %-5level %logger{36} - %msg%n"
